name: docker-odoo

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Check out code  
      
    - name: configure the environment
      run: |
       curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && sudo systemctl start docker
       
    - name: compile images to multiple platforms
      run: | 
       cd apps/odoo
       docker buildx build --platform linux/arm64 -t websoft9dev/odoo --push . 
       
       
       

